### ISSUE TITLE
Why do we have to pass data two times?

### ISSUE THREAD

**Issue by Qazalbash** [kazewong/flowMC#173]
During initialization [`flowMC.Sampler`](https://github.com/kazewong/flowMC/blob/94eee83d58afb31b981c3e3cd2d82de6692b8df5/src/flowMC/Sampler.py#L90) asks for `data` that will be passed to the `logpdf`, [`flowMC.Sampler.sample`](https://github.com/kazewong/flowMC/blob/94eee83d58afb31b981c3e3cd2d82de6692b8df5/src/flowMC/Sampler.py#L176) method also asks for `data` that will be passed to the `logpdf`. Are they same or different, and if they are same then why should we pass it two time?

**Comment by kazewong** [comment]
The first declaration of data is used in pre-compilation if it is turned on. It might be removed in the future as we search for more ergonomic design
