### ISSUE TITLE
Zero Local Acceptance Rate but Good Global Acceptance

### ISSUE THREAD

**Issue by zeeshan5885** [kazewong/flowMC#186]
Hi @kazewong , we are using flowMC for population inference of BBH and facing a strange issue. We are not sure what went wrong. We tried various configurations for the sampler but local acceptance is always zero. However, the global acceptance rate and training chains are going in the right direction.

We have plots and details in this issue https://github.com/gwkokab/gwkokab/issues/263 . We would appreciate any insights regarding such an issue. 

Thanks

**Comment by kazewong** [comment]
Can you check whether your gradient is returning a non-nan value? Local sampler like MALA relies on the gradient to make a proposal.

**Comment by zeeshan5885** [comment]
Thanks @kazewong, our issue has been resolved, we were getting the `nan` gradient for a single parameter.
