### ISSUE TITLE
Whitening

### ISSUE THREAD

**Issue by marylou-gabrie** [kazewong/FlowMC#3]
Add option in RealNVP to have a mean and covariance for the base distribution
1. Add keyword argument to the class, with default to standard Gaussian
2. Modify sample method
3. Modify logprob method

**Comment by marylou-gabrie** [comment]
Another desirable feature - learning rate scheduling for the flow: warmup + scheduled decrease

**Comment by kazewong** [comment]
There is an option to pass whitening parameters to and `sample` and `log_prob` now.
However, the flow trains worse when using the modified Gaussian as base distribution.
Need to investigate what went wrong.
