### ISSUE TITLE
Diagnostic

### ISSUE THREAD

**Issue by kazewong** [kazewong/flowMC#5]
Checkout https://arviz-devs.github.io/arviz/api/generated/arviz.from_dict.html for diagnostics

**Comment by kazewong** [comment]
Get these diagnostics ready:

1. Trace plot
2. Corner plot
3. Acceptances
4. Loss
5. R_hat (variance across chains)
6. Autocorrelation plot

**Comment by marylou-gabrie** [comment]
The diagnostics above are easily implemented using the arviz package. Examples are provided in the tutorials.
