### ISSUE TITLE
Unify the API for the different model of flows

### ISSUE THREAD

**Issue by marylou-gabrie** [kazewong/flowMC#65]
- RealNVP and RQSpline don't take their arguments in the same order (especially flipping the two first)
- RQSpline take a list hidden widths while RealNVP takes only one, imposing also the depth of the MLPs to 1-hidden layer.
- It would be useful to provide default values to model parameters. 

The tutorials would need to be updated after such changes.

**Comment by kazewong** [comment]
This is now solved in the newest update in #123
