### ISSUE TITLE
No separate requirements specified for tests

### ISSUE THREAD

**Issue by matt-graham** [kazewong/flowMC#76]
Raising issue as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5021

The tests seem to have additional dependencies beyond those of the `flowMC` package - for example `test/test_normalizingFlow.py` imports from `sklearn`, `optax` and `matplotlib`, none of which are specified in the requirements in the `README.md` or `setup.cfg` files. 

It would be useful to document the additional requirements for running the tests - for example by [adding an `[options.extras_require]` section to the `setup.cfg` file](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#configuring-setup-using-setup-cfg-files) with the additional test dependencies and/or listing the dependencies for running the tests in the `README.md` file.

**Comment by marylou-gabrie** [comment]
Thanks for raising this issue. PR #95 will fix this issue by restructuring tests and removing additional requirements except from `optax ` which is actually itself a requirement installed by `flax`.

**Comment by matt-graham** [comment]
Thanks for fixing. 

With regards to `optax`, not a big issue but I would say any module you directly import its worth explicitly including in requirements rather than relying on its being indirectly installed because it is a dependency of another dependency (`flax`), as this guard against the possibility of `optax` being removed as a dependency by `flax` in some future version.
