### ISSUE TITLE
No documentation of how to run tests

### ISSUE THREAD

**Issue by matt-graham** [kazewong/flowMC#77]
Raising issue as part of JOSS review https://github.com/openjournals/joss-reviews/issues/5021

There are what appear to be a set of tests in the `test` directory at the root of the repository but there are no details given that I can see of how these are expected to be run - for example is it expected that `pytest` is used to run the tests?

**Comment by kazewong** [comment]
Indeed `pytest` is used to run the tests. We have added a sentence in the requirement section of the README related to this issue in commit #7064998d90bbc96858b70bd4fe43a21f1aeee45a
